
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task-example2
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "This is step one of our second simple task example"
    - name: echo2
      image: ubuntu
      command:
        - echo
      args:
        - "This is step two of our second simple task example"
